from Class1 import Question

questions = [
    Question("What is the only food that cannot go bad?\n(a) Canned beans\n(b) Peanut butter\n(c) Chocolate\n(d) Honey", "d"),
    Question("What is the most visited tourist attraction in the world?\n(a) Eiffel Tower\n(b) Statue of Liberty\n(c) Great Wall of China\n(d) Colosseum.", "a"),
    Question("What’s the name of Hagrid’s pet spider?\n(a) Nigini\n(b) Crookshanks\n(c) Aragog.\n(d) Mosag", "c"),
    Question("What’s the heaviest organ in the human body?\n(a) Brain\n(b) Liver.\n(c) Skin\n(d) Heart", "b"),
    Question("Which of these EU countries does not use the euro as its currency?\n(a) Poland\n(b) Denmark\n(c) Sweden\n(d) All of the above", "d"),
    Question("What element does the chemical symbol Au stand for?\n(a) Silver\n(b) Magnesium\n(c) Salt\n(d) Gold", "d"),
    Question("On average, how many seeds are located on the outside of a strawberry?\n(a) 100\n(b) 200.\n(c) 400\n(d) 500", "b"),
    Question("In what country do more than half of people believe in elves?\n(a) Norway\n(b) Russia\n(c) Holland\n(d) Iceland", "d"),
    Question("Which country’s national animal is a unicorn?\n(a) Scotland.\n(b) Denmark\n(c) New Zealand\n(d) France", "a"),
    Question("What is the main ingredient in a falafel?\n(a) Lentil\n(b) Chickpea.\n(c) Broccoli\n(d) Split pea", "b"),
    Question("What color dresses do Chinese women traditionally wear on their wedding day?\n(a) Blue\n(b) Gold\n(c) White\n(d) Red", "d"),
    Question("What sport has been played on the moon?\n(a) Frisbee\n(b) Soccer\n(c) Golf.\n(d) Bocce ball", "c"),
    Question("Mycology is the scientific study of what?\n(a) Cancer cells\n(b) Flowers\n(c) Fungi.\n(d) Blood", "c"),
    Question("What animal is the closest living relative of a human?\n(a) Gorillas\n(b) Monkeys\n(c) Bonobos\n(d) Homo sapiens", "c"),
    Question("The first vaccine was for which disease?\n(a) Chickenpox\n(b) Polio\n(c) Measles\n(d) Smallpox", "d"),
    Question("What is the largest planet in our solar system?\n(a) Jupiter\n(b) Saturn\n(c) Mars\n(d) Venus", "a"),
    Question("Who painted the Mona Lisa?\n(a) Vincent van Gogh\n(b) Leonardo da Vinci\n(c) Pablo Picasso\n(d) Michelangelo", "b"),
    Question("What is the capital city of Australia?\n(a) Sydney\n(b) Melbourne\n(c) Canberra\n(d) Perth", "c"),
    Question("How many continents are there in the world?\n(a) 4\n(b) 6\n(c) 7\n(d) 9", "c"),
    Question("Who wrote the play 'Romeo and Juliet'?\n(a) William Shakespeare\n(b) Charles Dickens\n(c) Jane Austen\n(d) F. Scott Fitzgerald", "a"),
    Question("What is the chemical symbol for oxygen?\n(a) O\n(b) Au\n(c) Ag\n(d) H2", "a"),
    Question("What is the tallest mountain in the world?\n(a) Mount Everest\n(b) K2\n(c) Mount Kilimanjaro\n(d) Mount Fuji", "a"),
    Question("What is the largest ocean on Earth?\n(a) Pacific Ocean\n(b) Atlantic Ocean\n(c) Indian Ocean\n(d) Arctic Ocean", "a"),
    Question("Who painted the famous artwork 'The Starry Night'?\n(a) Pablo Picasso\n(b) Vincent van Gogh\n(c) Leonardo da Vinci\n(d) Claude Monet", "b"),
    Question("Which planet is known as the 'Red Planet'?\n(a) Mars\n(b) Jupiter\n(c) Saturn\n(d) Uranus", "a"),
    Question("What is the largest species of shark?\n(a) Great White Shark\n(b) Tiger Shark\n(c) Hammerhead Shark\n(d) Whale Shark", "d"),
    Question("Who is the author of the Harry Potter book series?\n(a) J.K. Rowling\n(b) Stephen King\n(c) George R.R. Martin\n(d) Dan Brown", "a")
]
